# For more information: https://laravel.com/docs/sail
version: '3'
services:
  nginx-ims-iu:
    build:
      context: "./.deploy/docker/nginx"
    restart: unless-stopped
    depends_on:
      - php-fpm-ims-iu
    volumes:
      - ./:/var/www/html
    ports:
      - "9530:80"

  php-fpm-ims-iu:
    build:
      context: "./.deploy/docker/php-fpm"
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"

  mysql-ims-iu:
    image: 'mysql/mysql-server:8.0'
    restart: unless-stopped
    ports:
      - "3530:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './volumes/mysql:/var/lib/mysql'
      - './.deploy/docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p123456" ]
      retries: 3
      timeout: 5s

  phpmyadmin-ims-iu:
    image: phpmyadmin
    depends_on:
      - mysql-ims-iu
    restart: unless-stopped
    ports:
      - "9531:80"
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=2G

# Docker Volumes
volumes:
  mysql:
    driver: local
